<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <LangVersion>8.0</LangVersion>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>GreenBoy.Windows</RootNamespace>
    <AssemblyName>GreenBoy.Windows</AssemblyName>
    <StartupObject>GreenBoy.Windows.Program</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreenBoy\GreenBoy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="WinFormsEmulatorSurface.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>